### ISSUE TITLE
Sample code

### ISSUE THREAD

**Issue by hodlerhacks** [oOthkOo/supervizer#10]
This project looks interesting and may be exactly what I need. I was wondering, do you have some sample code that shows how to use the REST API, especially how to start a node application with arguments, i.e. 'node app myargs' through the REST API. That would help me a lot. Also, I assume it's possible to start a node application from within another node application (without using the REST API) with your package, right? What is the javascript syntax to start an application, again with arguments? Thanks for any help you can provide!

**Comment by oOthkOo** [comment]
Hi,

All you need is in this file : https://github.com/oOthkOo/supervizer/blob/master/bin/supervizer-client

Cheers
